version: 2
jobs:
  build:

    working_directory: ~/cassandra-lucene-index

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - run: mvn clean install -DoutputDirectory=/tmp/artifacts -Pdeb,rpm -Dcassandra.version=4.0.13

      - save_cache:
          paths:
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}

      - store_test_results:
          path: ~/cassandra-lucene-index/testsAT/target/surefire-reports

      - store_artifacts:
          path: /tmp/artifacts

      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - "cassandra-lucene-index-plugin-*.jar"
            - "cassandra-lucene-index-plugin_*.deb"
            - "cassandra-lucene-index-plugin-*.rpm"

  publish-github-release:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            set -xue
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^cassandra-4\.0.\d+-\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^cassandra-4\.0.\d+-\d+\.\d+\.\d+$/
